# Generated by Django 3.0.6 on 2020-08-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course_uploaded',
        ),
    ]
