# Generated by Django 3.0.6 on 2020-08-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_teacher_course_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course_uploaded',
            field=models.CharField(default='None', max_length=100, verbose_name='courses.Course'),
        ),
    ]
