# Generated by Django 3.0.6 on 2020-08-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_video_video_file'),
        ('users', '0003_teacher_course_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course_uploaded',
            field=models.ForeignKey(default='None', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
