# Generated by Django 3.1 on 2020-08-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200807_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course_uploaded',
            field=models.CharField(max_length=100),
        ),
    ]
